# =============================================================================
# 🛡️ NEXORA-CORE - GOLANGCI-LINT CONFIGURATION (v1.60+)
# =============================================================================

run:
  # Timeout pour éviter que le CI ne tourne indéfiniment
  timeout: 5m
  # Ne pas modifier go.mod pendant le lint
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    # --- Standard Linters ---
    - errcheck      # Vérifie les erreurs non gérées
    - gosimple      # Suggère des simplifications de code
    - govet         # Analyse statique officielle de Go
    - ineffassign   # Détecte les assignations inutiles
    - staticcheck   # Analyse statique avancée
    - typecheck     # Vérifie les types (comme le compilateur)
    - unused        # Détecte le code mort (variables/fonctions non utilisées)
    
    # --- Code Style ---
    - gofmt         # Vérifie le formatage standard
    
    # --- Complexité & Bugs ---
    - goconst       # Trouve les chaînes répétées qui devraient être des constantes

linters-settings:
  govet:
    # ✅ NOUVELLE SYNTAXE (Remplace check-shadowing: true)
    enable:
      - shadow
  
  gofmt:
    simplify: true

issues:
  # Exclure certains dossiers générés ou de tests si besoin
  exclude-dirs:
    - docs
    - bin